version: 2.1

orbs:
  ruby-orbs: sue445/ruby-orbs@dev:963a40072f0034dcd56e69eb972c6ef4cac4afa3

jobs:
  bundle-install-test:
    docker:
      - image: circleci/ruby:2.7
    working_directory: ~/app
    steps:
      - checkout

      - run: ruby -v
      - run: bundle -v

      - ruby-orbs/bundle-install:
          cache_key_prefix: "v1-bundle"
          bundle_jobs: 4
          bundle_retry: 3
          bundle_path: "vendor/bundle"
          bundle_gemfile: "Gemfile"
          bundle_clean: true
          restore_bundled_with: true

  branch_cleaner:
    docker:
      - image: circleci/ruby:2.7
    working_directory: ~/app
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
          - "c0:a3:f0:56:75:7f:b0:4d:d1:19:39:08:0e:0e:5a:31"
      - run: ruby .circleci/branch_cleaner.rb 12

workflows:
  version: 2

  smoke_test:
    jobs:
      - bundle-install-test
      - ruby-orbs/bundle-update-pr:
          image: "circleci/ruby:2.7"
          pre-bundle-update-pr:
            - run:
                name: "Set timezone to Asia/Tokyo"
                command: sudo cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime
            - ruby-orbs/bundle-install
          assignees: "sue445-test"
          git_user_name:  "CircleCI bundle updater"

  branch_cleaner:
    triggers:
      - schedule:
          cron: "0 0,12 * * *"
          filters:
            branches:
              only: master
    jobs:
      - branch_cleaner

  nightly:
    triggers:
      - schedule:
          cron: "00 10 * * 5"
          filters:
            branches:
              only: master

    jobs:
      - ruby-orbs/bundle-update-pr:
          image: "circleci/ruby:2.7"
          pre-bundle-update-pr:
            - run:
                name: "Set timezone to Asia/Tokyo"
                command: sudo cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime
            - ruby-orbs/bundle-install
          assignees: "sue445"
          git_user_name:  "CircleCI bundle updater"
